[2023-10-23 21:10:41] [error] [E:\桌面\不同步文件\文创\main.py - 63 - <module>] 光照强度数据读取失败,错误原因为Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
[2023-10-23 21:13:13] [error] [E:\桌面\不同步文件\文创\main.py - 80 - <module>] 电网购电数据读取失败,错误原因为single positional indexer is out-of-bounds
[2023-10-25 16:17:30] [error] [E:\桌面\不同步文件\文创\main.py - 33 - tanpai] 输出碳流图相关变量失败,错误原因为'str' object has no attribute 'cell'
[2023-10-25 16:17:30] [error] [E:\桌面\不同步文件\文创\main.py - 67 - <module>] 碳流图模块运行失败,错误原因为
[2023-10-25 16:27:54] [error] [E:\桌面\不同步文件\文创\main.py - 77 - <module>] 碳流图模块运行失败,错误原因为list index out of range
[2023-10-25 16:47:53] [error] [E:\桌面\不同步文件\文创\main.py - 47 - tanpai] 输出碳流图相关变量失败,错误原因为'int' object is not iterable
[2023-10-25 16:47:53] [error] [E:\桌面\不同步文件\文创\main.py - 81 - <module>] 碳流图模块运行失败,错误原因为
[2023-10-25 16:57:58] [error] [E:\桌面\不同步文件\文创\main.py - 47 - tanpai] 输出碳流图相关变量失败,错误原因为
[2023-10-25 16:57:58] [error] [E:\桌面\不同步文件\文创\main.py - 81 - <module>] 碳流图模块运行失败,错误原因为
[2023-10-25 16:58:39] [error] [E:\桌面\不同步文件\文创\main.py - 81 - <module>] 碳流图模块运行失败,错误原因为"There is no item named '[Content_Types].xml' in the archive"
[2023-10-25 17:03:29] [error] [E:\桌面\不同步文件\文创\main.py - 47 - tanpai] 输出碳流图相关变量失败,错误原因为
[2023-10-25 17:03:29] [error] [E:\桌面\不同步文件\文创\main.py - 81 - <module>] 碳流图模块运行失败,错误原因为
[2023-10-25 22:39:03] [error] [E:\桌面\不同步文件\文创\main.py - 82 - <module>] 碳流图模块运行失败,错误原因为"There is no item named '[Content_Types].xml' in the archive"
[2023-10-25 22:39:15] [error] [E:\桌面\不同步文件\文创\main.py - 82 - <module>] 碳流图模块运行失败,错误原因为"There is no item named '[Content_Types].xml' in the archive"
[2023-10-25 22:40:38] [error] [E:\桌面\不同步文件\文创\main.py - 82 - <module>] 碳流图模块运行失败,错误原因为list index out of range
[2023-10-25 22:40:59] [error] [E:\桌面\不同步文件\文创\main.py - 48 - tanpai] 输出碳流图相关变量失败,错误原因为Worksheet.cell() missing 1 required positional argument: 'column'
[2023-10-25 22:40:59] [error] [E:\桌面\不同步文件\文创\main.py - 82 - <module>] 碳流图模块运行失败,错误原因为
[2023-10-25 22:46:01] [error] [E:\桌面\不同步文件\文创\main.py - 48 - tanpai] 输出碳流图相关变量失败,错误原因为Row or column values must be at least 1
[2023-10-25 22:46:01] [error] [E:\桌面\不同步文件\文创\main.py - 82 - <module>] 碳流图模块运行失败,错误原因为
[2023-10-25 22:48:32] [error] [E:\桌面\不同步文件\文创\main.py - 48 - tanpai] 输出碳流图相关变量失败,错误原因为
[2023-10-25 22:48:32] [error] [E:\桌面\不同步文件\文创\main.py - 82 - <module>] 碳流图模块运行失败,错误原因为
[2023-11-22 16:04:52] [error] [E:\桌面\不同步文件\碳排放测算\main.py - 60 - tanpai] 输出碳排放相关变量失败,错误原因为'Worksheet' object has no attribute 'save'
[2023-11-22 16:04:52] [error] [E:\桌面\不同步文件\碳排放测算\main.py - 77 - <module>] 碳排放测算模块运行失败,错误原因为
[2023-11-22 16:16:13] [error] [E:\桌面\不同步文件\碳排放测算\main.py - 60 - tanpai] 输出碳排放相关变量失败,错误原因为'Worksheet' object has no attribute 'save'
[2023-11-22 16:16:13] [error] [E:\桌面\不同步文件\碳排放测算\main.py - 77 - <module>] 碳排放测算模块运行失败,错误原因为
[2023-11-22 16:20:37] [error] [E:\桌面\不同步文件\碳排放测算\main.py - 80 - <module>] 碳排放测算模块运行失败,错误原因为'list' object is not callable
[2023-11-22 16:25:19] [error] [E:\桌面\不同步文件\碳排放测算\main.py - 79 - <module>] 碳排放测算模块运行失败,错误原因为'Workbook' object has no attribute 'sheet_names'
[2023-11-22 16:25:45] [error] [E:\桌面\不同步文件\碳排放测算\main.py - 79 - <module>] 碳排放测算模块运行失败,错误原因为'list' object is not callable
[2023-11-22 16:26:54] [error] [E:\桌面\不同步文件\碳排放测算\main.py - 79 - <module>] 碳排放测算模块运行失败,错误原因为'Workbook' object has no attribute 'sheetname'
[2023-11-22 16:27:34] [error] [E:\桌面\不同步文件\碳排放测算\main.py - 79 - <module>] 碳排放测算模块运行失败,错误原因为'list' object is not callable
[2023-11-22 16:29:08] [error] [E:\桌面\不同步文件\碳排放测算\main.py - 79 - <module>] 碳排放测算模块运行失败,错误原因为'list' object is not callable
[2023-11-22 16:31:41] [error] [E:\桌面\不同步文件\碳排放测算\main.py - 79 - <module>] 碳排放测算模块运行失败,错误原因为'Workbook' object has no attribute 'sheetname'
[2023-11-22 16:43:38] [error] [E:\桌面\不同步文件\碳排放测算_仿真\main.py - 61 - <module>] 电网购电数据读取失败,错误原因为name 'pd' is not defined
[2023-11-22 16:50:29] [error] [E:\桌面\不同步文件\碳排放测算_仿真\main.py - 52 - tanpai] 输出碳排放相关变量失败,错误原因为[Errno 13] Permission denied: 'output/output.xlsx'
[2023-11-22 16:50:29] [error] [E:\桌面\不同步文件\碳排放测算_仿真\main.py - 69 - <module>] 碳排放测算模块运行失败,错误原因为
[2023-11-22 17:21:09] [error] [E:\桌面\不同步文件\碳排放测算\碳排放测算_测试\main.py - 53 - tanpai] 输出碳排放相关变量失败,错误原因为0
[2023-11-22 17:21:09] [error] [E:\桌面\不同步文件\碳排放测算\碳排放测算_测试\main.py - 87 - <module>] 碳排放测算模块运行失败,错误原因为
[2023-11-22 17:30:42] [error] [E:\桌面\不同步文件\碳排放测算\碳排放测算_测试\main.py - 53 - tanpai] 输出碳排放相关变量失败,错误原因为0
[2023-11-22 17:30:42] [error] [E:\桌面\不同步文件\碳排放测算\碳排放测算_测试\main.py - 87 - <module>] 碳排放测算模块运行失败,错误原因为
[2023-11-22 19:15:19] [error] [E:\桌面\不同步文件\碳排放测算\碳排放测算_测试\main.py - 75 - <module>] 电网购电数据读取失败,错误原因为Invalid file path or buffer object type: <class 'pandas.core.frame.DataFrame'>
[2023-11-22 19:16:01] [error] [E:\桌面\不同步文件\碳排放测算\碳排放测算_测试\main.py - 75 - <module>] 电网购电数据读取失败,错误原因为Invalid file path or buffer object type: <class 'pandas.core.frame.DataFrame'>
[2023-11-22 19:17:10] [error] [E:\桌面\不同步文件\碳排放测算\碳排放测算_测试\main.py - 75 - <module>] 电网购电数据读取失败,错误原因为Invalid file path or buffer object type: <class 'pandas.core.frame.DataFrame'>
[2023-11-22 19:34:23] [error] [E:\桌面\不同步文件\碳排放测算\碳排放测算_测试\main.py - 76 - <module>] 电网购电数据读取失败,错误原因为name 't_n_obix' is not defined
[2023-11-22 19:34:40] [error] [E:\桌面\不同步文件\碳排放测算\碳排放测算_测试\main.py - 76 - <module>] 电网购电数据读取失败,错误原因为name 'time_now' is not defined
[2023-11-22 19:34:50] [error] [E:\桌面\不同步文件\碳排放测算\碳排放测算_测试\main.py - 53 - tanpai] 输出碳排放相关变量失败,错误原因为0
[2023-11-22 19:34:50] [error] [E:\桌面\不同步文件\碳排放测算\碳排放测算_测试\main.py - 91 - <module>] 碳排放测算模块运行失败,错误原因为
[2023-11-22 19:35:21] [error] [E:\桌面\不同步文件\碳排放测算\碳排放测算_测试\main.py - 53 - tanpai] 输出碳排放相关变量失败,错误原因为0
[2023-11-22 19:35:21] [error] [E:\桌面\不同步文件\碳排放测算\碳排放测算_测试\main.py - 91 - <module>] 碳排放测算模块运行失败,错误原因为
[2023-11-22 20:02:55] [error] [E:\桌面\不同步文件\碳排放测算\碳排放测算_测试\main.py - 76 - <module>] 电网购电数据读取失败,错误原因为[Errno 13] Permission denied: 'input/input.xlsx'
[2023-11-22 20:05:36] [error] [E:\桌面\不同步文件\碳排放测算\碳排放测算_测试\main.py - 76 - <module>] 电网购电数据读取失败,错误原因为cannot access local variable 'data_tmp' where it is not associated with a value
[2023-11-22 20:05:59] [error] [E:\桌面\不同步文件\碳排放测算\碳排放测算_测试\main.py - 76 - <module>] 电网购电数据读取失败,错误原因为cannot access local variable 'data_tmp' where it is not associated with a value
[2023-11-22 21:00:59] [error] [E:\桌面\不同步文件\碳排放测算\碳排放测算_测试\main.py - 76 - <module>] 电网购电数据读取失败,错误原因为cannot access local variable 'data_tmp' where it is not associated with a value
[2023-11-22 21:01:35] [error] [E:\桌面\不同步文件\碳排放测算\碳排放测算_测试\main.py - 77 - <module>] 电网购电数据读取失败,错误原因为cannot access local variable 'data_tmp' where it is not associated with a value
[2023-11-22 21:04:55] [error] [E:\桌面\不同步文件\碳排放测算\碳排放测算_测试\main.py - 77 - <module>] 电网购电数据读取失败,错误原因为cannot access local variable 'data_tmp' where it is not associated with a value
[2023-11-22 21:07:03] [error] [E:\桌面\不同步文件\碳排放测算\碳排放测算_测试\main.py - 53 - tanpai] 输出碳排放相关变量失败,错误原因为1
